In [125]:
import pandas as pd
import scipy, researchpy
from researchpy import ttest
import os, glob
import numpy as np

In [193]:
import json
import mpu.io

data = {'fold_0': list_fold_0,
        'fold_1': list_fold_1,
        'fold_2': list_fold_2,
       }
print(json.dumps(data, indent=4))


mpu.io.write('gbm_seed.json', data)

{
    "fold_0": [
        "TCGA-02-0011",
        "TCGA-02-0033",
        "TCGA-02-0037",
        "TCGA-02-0047",
        "TCGA-02-0054",
        "TCGA-02-0069",
        "TCGA-02-0106",
        "TCGA-06-0137",
        "TCGA-06-0142",
        "TCGA-06-0162",
        "TCGA-06-0179",
        "TCGA-06-0185",
        "TCGA-06-0188",
        "TCGA-06-0192",
        "TCGA-06-0238",
        "TCGA-06-0644",
        "TCGA-06-0646",
        "TCGA-06-1084",
        "TCGA-06-2570",
        "TCGA-06-5408",
        "TCGA-08-0356",
        "TCGA-08-0359",
        "TCGA-08-0390",
        "TCGA-08-0520",
        "TCGA-08-0522",
        "TCGA-12-0829",
        "TCGA-12-1098",
        "TCGA-12-1601",
        "TCGA-14-1456",
        "TCGA-14-1825",
        "TCGA-14-3477",
        "TCGA-19-5960",
        "TCGA-76-4932",
        "TCGA-76-6282"
    ],
    "fold_1": [
        "TCGA-02-0006",
        "TCGA-02-0068",
        "TCGA-02-0085",
        "TCGA-02-0086",
        "TCGA-02-0087",
        "TCGA-02-0102",
        "TCGA-02-0116",
        "TCGA-06-0119",
        "TCGA-06-0130",
        "TCGA-06-0138",
        "TCGA-06-0139",
        "TCGA-06-0149",
        "TCGA-06-0158",
        "TCGA-06-0176",
        "TCGA-06-0184",
        "TCGA-06-0240",
        "TCGA-06-1802",
        "TCGA-06-5413",
        "TCGA-06-5417",
        "TCGA-08-0385",
        "TCGA-08-0392",
        "TCGA-08-0512",
        "TCGA-12-0616",
        "TCGA-12-0776",
        "TCGA-12-3650",
        "TCGA-19-2631",
        "TCGA-19-5951",
        "TCGA-19-5954",
        "TCGA-19-5958",
        "TCGA-76-4934",
        "TCGA-76-4935",
        "TCGA-76-6280",
        "TCGA-76-6656",
        "TCGA-76-6657"
    ],
    "fold_2": [
        "TCGA-02-0009",
        "TCGA-02-0027",
        "TCGA-02-0034",
        "TCGA-02-0046",
        "TCGA-02-0059",
        "TCGA-02-0064",
        "TCGA-02-0070",
        "TCGA-02-0075",
        "TCGA-06-0122",
        "TCGA-06-0145",
        "TCGA-06-0154",
        "TCGA-06-0164",
        "TCGA-06-0177",
        "TCGA-06-0182",
        "TCGA-06-0187",
        "TCGA-06-0190",
        "TCGA-06-6389",
        "TCGA-08-0355",
        "TCGA-08-0360",
        "TCGA-08-0389",
        "TCGA-08-0509",
        "TCGA-12-1094",
        "TCGA-12-1598",
        "TCGA-14-1794",
        "TCGA-19-0963",
        "TCGA-19-1789",
        "TCGA-19-2624",
        "TCGA-76-6191",
        "TCGA-76-6193",
        "TCGA-76-6285",
        "TCGA-76-6661",
        "TCGA-76-6662",
        "TCGA-76-6663",
        "TCGA-76-6664"
    ]
}

{'fold_0': ['TCGA-02-0011',
  'TCGA-02-0033',
  'TCGA-02-0037',
  'TCGA-02-0047',
  'TCGA-02-0054',
  'TCGA-02-0069',
  'TCGA-02-0106',
  'TCGA-06-0137',
  'TCGA-06-0142',
  'TCGA-06-0162',
  'TCGA-06-0179',
  'TCGA-06-0185',
  'TCGA-06-0188',
  'TCGA-06-0192',
  'TCGA-06-0238',
  'TCGA-06-0644',
  'TCGA-06-0646',
  'TCGA-06-1084',
  'TCGA-06-2570',
  'TCGA-06-5408',
  'TCGA-08-0356',
  'TCGA-08-0359',
  'TCGA-08-0390',
  'TCGA-08-0520',
  'TCGA-08-0522',
  'TCGA-12-0829',
  'TCGA-12-1098',
  'TCGA-12-1601',
  'TCGA-14-1456',
  'TCGA-14-1825',
  'TCGA-14-3477',
  'TCGA-19-5960',
  'TCGA-76-4932',
  'TCGA-76-6282'],
 'fold_1': ['TCGA-02-0006',
  'TCGA-02-0068',
  'TCGA-02-0085',
  'TCGA-02-0086',
  'TCGA-02-0087',
  'TCGA-02-0102',
  'TCGA-02-0116',
  'TCGA-06-0119',
  'TCGA-06-0130',
  'TCGA-06-0138',
  'TCGA-06-0139',
  'TCGA-06-0149',
  'TCGA-06-0158',
  'TCGA-06-0176',
  'TCGA-06-0184',
  'TCGA-06-0240',
  'TCGA-06-1802',
  'TCGA-06-5413',
  'TCGA-06-5417',
  'TCGA-08-0385',
  'TCGA-08-0392',
  'TCGA-08-0512',
  'TCGA-12-0616',
  'TCGA-12-0776',
  'TCGA-12-3650',
  'TCGA-19-2631',
  'TCGA-19-5951',
  'TCGA-19-5954',
  'TCGA-19-5958',
  'TCGA-76-4934',
  'TCGA-76-4935',
  'TCGA-76-6280',
  'TCGA-76-6656',
  'TCGA-76-6657'],
 'fold_2': ['TCGA-02-0009',
  'TCGA-02-0027',
  'TCGA-02-0034',
  'TCGA-02-0046',
  'TCGA-02-0059',
  'TCGA-02-0064',
  'TCGA-02-0070',
  'TCGA-02-0075',
  'TCGA-06-0122',
  'TCGA-06-0145',
  'TCGA-06-0154',
  'TCGA-06-0164',
  'TCGA-06-0177',
  'TCGA-06-0182',
  'TCGA-06-0187',
  'TCGA-06-0190',
  'TCGA-06-6389',
  'TCGA-08-0355',
  'TCGA-08-0360',
  'TCGA-08-0389',
  'TCGA-08-0509',
  'TCGA-12-1094',
  'TCGA-12-1598',
  'TCGA-14-1794',
  'TCGA-19-0963',
  'TCGA-19-1789',
  'TCGA-19-2624',
  'TCGA-76-6191',
  'TCGA-76-6193',
  'TCGA-76-6285',
  'TCGA-76-6661',
  'TCGA-76-6662',
  'TCGA-76-6663',
  'TCGA-76-6664']}

In [261]:
folder = 'log_gbm/results'
# '../{}/*{}*'.format(folder, exp)

In [276]:
data = pd.read_csv('paths_to_csv.txt', header = None)
import shlex, subprocess,time
base_command = """scp gpu_server_kate:{path} /home/kate/projects/brain-mri-processing-pipeline/main_pipeline/log_gbm/results/ """
for i in range(0,len(data)):
    print(data[0].iloc[i])
    command_to_run = base_command.format(path = data[0].iloc[i])
    command_to_run = shlex.split(command_to_run)
    process = subprocess.Popen(command_to_run,shell=False)
    time.sleep(1)

/mnt/experiments/gbm_infer/2a_interp/metrics_gbm_2a_interp_fold-0.csv
/mnt/experiments/gbm_infer/2a_interp/metrics_gbm_2a_interp_fold-2.csv
/mnt/experiments/gbm_infer/2a_interp/metrics_gbm_2a_interp_fold-1.csv
/mnt/experiments/gbm_infer/2a_interp_aug/metrics_gbm_3aatlas_withoutbrain_label_from_3aatlas_fold-1.csv
/mnt/experiments/gbm_infer/2a_interp_aug/metrics_gbm_3aatlas_withoutbrain_label_from_3aatlas_fold-2.csv
/mnt/experiments/gbm_infer/2a_interp_aug/metrics_gbm_3aatlas_withoutbrain_label_from_3aatlas_fold-0.csv
/mnt/experiments/gbm_infer/2a_interp_aug/metrics_gbm_2a_interp_aug_fold-2.csv
/mnt/experiments/gbm_infer/2a_interp_aug/metrics_gbm_2a_interp_aug_fold-1.csv
/mnt/experiments/gbm_infer/2a_interp_aug/metrics_gbm_2a_interp_aug_fold-0.csv
/mnt/experiments/gbm_infer/3b_n4/metrics_gbm_3b_n4_fold-1.csv
/mnt/experiments/gbm_infer/3b_n4/metrics_gbm_3b_n4_fold-0.csv
/mnt/experiments/gbm_infer/3b_n4/metrics_gbm_3b_n4_fold-2.csv
/mnt/experiments/gbm_infer/6_histogram_fold_0_old/metrics_gbm_6_histogram_fold_0_fold-0.csv
/mnt/experiments/gbm_infer/6_histogram_fold_2_old/metrics_gbm_6_histogram_fold_2_fold-2.csv
/mnt/experiments/gbm_infer/3a_susan/metrics_gbm_3a_susan_fold-1.csv
/mnt/experiments/gbm_infer/3a_susan/metrics_gbm_3a_susan_fold-2.csv
/mnt/experiments/gbm_infer/1_reg/metrics_gbm_1_reg_fold-1.csv
/mnt/experiments/gbm_infer/1_reg/metrics_gbm_1_reg_fold-0.csv
/mnt/experiments/gbm_infer/1_reg/metrics_gbm_1_reg_fold-2.csv
/mnt/experiments/gbm_infer/TCGA_GBM/metrics_gbm_TCGA_GBM_fold-1.csv
/mnt/experiments/gbm_infer/TCGA_GBM/metrics_gbm_TCGA_GBM_fold-2.csv
/mnt/experiments/gbm_infer/7a_resample_aug_300/metrics_gbm_7a_resample_aug_300_fold-0.csv
/mnt/experiments/gbm_infer/7a_resample_aug_300/metrics_gbm_7a_resample_aug_300_fold-2.csv
/mnt/experiments/gbm_infer/7a_resample_aug_300/metrics_gbm_7a_resample_aug_300_fold-1.csv
/mnt/experiments/gbm_infer/gbm_3a_atlas/metrics_gbm_3a_atlas_fold-0.csv
/mnt/experiments/gbm_infer/gbm_3a_atlas/metrics_gbm_3a_atlas_fold-2.csv
/mnt/experiments/gbm_infer/gbm_3a_atlas/metrics_gbm_3a_atlas_fold-1.csv
/mnt/experiments/gbm_infer/3a_atlas_aug_300/metrics_gbm_3a_atlas_aug_300_fold-0.csv
/mnt/experiments/gbm_infer/3a_atlas_aug_300/metrics_gbm_3a_atlas_aug_300_fold-2.csv
/mnt/experiments/gbm_infer/3a_atlas_aug_300/metrics_gbm_3a_atlas_aug_300_fold-1.csv
/mnt/experiments/gbm_infer/6_histogram_fold_1_old/metrics_gbm_6_histogram_fold_1_fold-1.csv
/mnt/experiments/gbm_infer/5_ss_shared/metrics_gbm_5_ss_shared_fold-2.csv
/mnt/experiments/gbm_infer/5_ss_shared/metrics_gbm_5_ss_shared_fold-1.csv
/mnt/experiments/gbm_infer/5_ss_shared/metrics_gbm_{5_ss_shared}_fold-0.csv

protocol error: filename does not match request

/mnt/experiments/gbm_infer/5_ss_shared/metrics_gbm_5_ss_shared_fold-1_label_from_3atlas.csv
/mnt/experiments/gbm_infer/5_ss_shared/metrics_gbm_5_ss_shared_fold-2_label_from_3atlas.csv
/mnt/experiments/gbm_infer/5_ss_shared/metrics_gbm_5_ss_shared_fold-0_label_from_3atlas.csv
/mnt/experiments/gbm_infer/2c_n4_susan/metrics_gbm_2c_n4_susan_fold-2.csv
/mnt/experiments/gbm_infer/2c_n4_susan/metrics_gbm_2c_n4_susan_fold-0.csv
/mnt/experiments/gbm_infer/2c_n4_susan/metrics_gbm_2c_n4_susan_fold-1.csv
/mnt/experiments/gbm_infer/7a_resample/metrics_gbm_7a_resample_fold-2.csv
/mnt/experiments/gbm_infer/7a_resample/metrics_gbm_7a_resample_fold-1.csv
/mnt/experiments/gbm_infer/7a_resample/metrics_gbm_7a_resample_fold-0.csv
/mnt/experiments/gbm_infer/3c_n4_susan/metrics_gbm_3c_n4_susan_fold-1.csv
/mnt/experiments/gbm_infer/3c_n4_susan/metrics_gbm_3c_n4_susan_fold-2.csv
/mnt/experiments/gbm_infer/3c_n4_susan/metrics_gbm_3c_n4_susan_fold-0.csv
/mnt/experiments/gbm_infer/2b_n4/metrics_gbm_2b_n4_fold-0.csv
/mnt/experiments/gbm_infer/2b_n4/metrics_gbm_2b_n4_fold-2.csv
/mnt/experiments/gbm_infer/2b_n4/metrics_gbm_2b_n4_fold-1.csv
/mnt/experiments/gbm_infer/1_reg_aug/metrics_gbm_1_reg_aug_fold-2.csv
/mnt/experiments/gbm_infer/1_reg_aug/metrics_gbm_1_reg_aug_fold-1.csv
/mnt/experiments/gbm_infer/1_reg_aug/metrics_gbm_1_reg_aug_fold-0.csv

In [264]:
def make_df_fold(folder, exp, df_fold_0, df_fold_1, df_fold_2):
    """ for most of experiments name of experiment `exp` should include `_f`
    """
    assert(len(glob.glob('../{}/*{}*'.format(folder, exp))) == 3, 'missing files')
    for fold in glob.glob('../{}/*{}*'.format(folder, exp)):
        if 'fold-0' in fold:
            df_fold_0 = pd.read_csv(fold)
            df_fold_0 = df_fold_0[df_fold_0['Ids'].isin(list_fold_0)]
        elif 'fold-1' in fold:
            df_fold_1 = pd.read_csv(fold)
            df_fold_1 = df_fold_1[df_fold_1['Ids'].isin(list_fold_1)]
        elif 'fold-2' in fold:                  
            df_fold_2 = pd.read_csv(fold)
            df_fold_2 = df_fold_2[df_fold_2['Ids'].isin(list_fold_2)]
    result_df = pd.concat([df_fold_0,df_fold_1,df_fold_2])
    result_df = result_df.drop(result_df.columns[0], axis = 1).reset_index(drop=True)
    return result_df

<>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
/tmp/ipykernel_495617/1822496527.py:4: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert(len(glob.glob('../{}/*{}*'.format(folder, exp))) == 3, 'missing files')

In [253]:
df_1 = make_df_fold('log_gbm/results','1_reg_f', df_fold_0, df_fold_1, df_fold_2)
df_2 = make_df_fold('log_gbm/results','1_reg_aug', df_fold_0, df_fold_1, df_fold_2)

In [226]:
def ttest_pair(metric, df_1, df_2, name_1, name_2, correction = None):
    return ttest(df_1[metric], df_2[metric], group1_name = name_1,
                 group2_name= name_2, equal_variances=False, paired=True, correction = 8).iloc[4].values[1]

In [255]:
ttest_pair('Dice_1', df_1, df_2, '1_reg_f', '1_reg_aug')

0.0456

In [265]:
fixed = '1_reg_f'
moving = '1_reg_aug'
metrics = ['Dice_1']
result = pd.DataFrame()
df_1 = make_df_fold(folder, fixed, df_fold_0, df_fold_1, df_fold_2)
    
for exp in moving:
    df_2 = make_df_fold(folder, exp, df_fold_0, df_fold_1, df_fold_2)
    for metric in metrics:
            
        result = result.append({'Experiment': fixed,
                                    'Metric' : metric,
                                    'Mean': np.round(df_1[metric].mean(),3),
                                    'STD': np.round(df_1[metric].std(),3)},  
                                   ignore_index = True)
        p_value = ttest_pair(metric, df_1, df_2, fixed, exp, correction = len(moving))
        result = result.append({'Experiment': exp,
                                    'Metric' : metric,
                                    'Mean': np.round(df_2[metric].mean(),3),
                                    'STD': np.round(df_2[metric].std(),3),
                                    'p_value': np.round(p_value,3),
                                    'criterion' : (p_value < 0.050),
                                    },  
                                   ignore_index = True)

In [269]:
def make_main_table(folder, fixed, moving, metrics, df_fold_0, df_fold_1, df_fold_2):
    result = pd.DataFrame()
    df_1 = make_df_fold(folder,fixed, df_fold_0, df_fold_1, df_fold_2)
    
    for exp in moving:
        df_2 = make_df_fold(folder,exp, df_fold_0, df_fold_1, df_fold_2)
        for metric in metrics:
            
            result = result.append({'Experiment': fixed,
                                    'Metric' : metric,
                                    'Mean': np.round(df_1[metric].mean(),3),
                                    'STD': np.round(df_1[metric].std(),3)},  
                                   ignore_index = True)
            p_value = ttest_pair(metric, df_1, df_2, fixed, exp, correction = len(moving))
            result = result.append({'Experiment': exp,
                                    'Metric' : metric,
                                    'Mean': np.round(df_2[metric].mean(),3),
                                    'STD': np.round(df_2[metric].std(),3),
                                    'p_value': np.round(p_value,3),
                                    'criterion' : (p_value < 0.050),
                                    },  
                                   ignore_index = True)
    return result

In [270]:
make_main_table(folder, '1_reg', ['1_reg_aug'],
                ['Dice_1'], 
                df_fold_0, df_fold_1, df_fold_2).drop_duplicates(['Experiment','Metric' ]).sort_values(['Mean'])

  Experiment  Metric   Mean    STD  criterion  p_value
1  1_reg_aug  Dice_1  0.430  0.270        0.0    0.786
0      1_reg  Dice_1  0.431  0.271        NaN      NaN

In [271]:
make_main_table(folder, '3a_atlas_f', ['7a_resample', '3b_n4_f','3a_susan','3c_n4_susan','6_histogram', '5_ss_shared'],
                ['Surface_dice_1'], df_fold_0, df_fold_1, df_fold_2).drop_duplicates(['Experiment']).sort_values(['Mean'])

     Experiment          Metric   Mean    STD  criterion  p_value
5      3a_susan  Surface_dice_1  0.535  0.256        1.0    0.000
9   6_histogram  Surface_dice_1  0.581  0.183        1.0    0.000
7   3c_n4_susan  Surface_dice_1  0.625  0.200        1.0    0.000
3       3b_n4_f  Surface_dice_1  0.638  0.199        1.0    0.001
1   7a_resample  Surface_dice_1  0.642  0.196        1.0    0.000
0    3a_atlas_f  Surface_dice_1  0.668  0.195        NaN      NaN
11  5_ss_shared  Surface_dice_1  0.700  0.187        1.0    0.013

In [188]:
make_main_table(folder,'7a_resample' , ['3a_atlas_f','2a_interp_f', ],
                ['Dice_1','Surface_dice_1','Sensitivity_1','Precision_1'], 
                df_fold_0, df_fold_1, df_fold_2).drop_duplicates(['Experiment','Metric' ])

     Experiment          Metric   Mean    STD  criterion  p_value
0   7a_resample          Dice_1  0.848  0.111        NaN      NaN
1    3a_atlas_f          Dice_1  0.857  0.106        1.0    0.001
2   7a_resample  Surface_dice_1  0.642  0.196        NaN      NaN
3    3a_atlas_f  Surface_dice_1  0.668  0.195        1.0    0.000
4   7a_resample   Sensitivity_1  0.861  0.136        NaN      NaN
5    3a_atlas_f   Sensitivity_1  0.869  0.126        0.0    0.219
6   7a_resample     Precision_1  0.854  0.123        NaN      NaN
7    3a_atlas_f     Precision_1  0.862  0.121        0.0    0.068
9   2a_interp_f          Dice_1  0.853  0.107        0.0    0.224
11  2a_interp_f  Surface_dice_1  0.498  0.180        1.0    0.000
13  2a_interp_f   Sensitivity_1  0.849  0.138        1.0    0.000
15  2a_interp_f     Precision_1  0.874  0.112        1.0    0.000

In [189]:
make_main_table(folder,'3a_atlas_f' , ['3b_n4_f','3a_susan','3c_n4_susan','6_histogram','5_ss_shared'],
                ['Dice_1','Surface_dice_1','Sensitivity_1','Precision_1'], 
                df_fold_0, df_fold_1, df_fold_2).drop_duplicates(['Experiment','Metric' ])

     Experiment          Metric   Mean    STD  criterion  p_value
0    3a_atlas_f          Dice_1  0.857  0.106        NaN      NaN
1       3b_n4_f          Dice_1  0.844  0.113        1.0    0.019
2    3a_atlas_f  Surface_dice_1  0.668  0.195        NaN      NaN
3       3b_n4_f  Surface_dice_1  0.638  0.199        1.0    0.001
4    3a_atlas_f   Sensitivity_1  0.869  0.126        NaN      NaN
5       3b_n4_f   Sensitivity_1  0.852  0.145        0.0    0.496
6    3a_atlas_f     Precision_1  0.862  0.121        NaN      NaN
7       3b_n4_f     Precision_1  0.857  0.124        0.0    0.080
9      3a_susan          Dice_1  0.723  0.245        1.0    0.001
11     3a_susan  Surface_dice_1  0.535  0.256        1.0    0.000
13     3a_susan   Sensitivity_1  0.703  0.292        1.0    0.000
15     3a_susan     Precision_1  0.834  0.151        0.0    0.226
17  3c_n4_susan          Dice_1  0.839  0.118        1.0    0.000
19  3c_n4_susan  Surface_dice_1  0.625  0.200        1.0    0.000
21  3c_n4_susan   Sensitivity_1  0.854  0.145        0.0    0.373
23  3c_n4_susan     Precision_1  0.848  0.132        0.0    0.058
25  6_histogram          Dice_1  0.829  0.114        1.0    0.000
27  6_histogram  Surface_dice_1  0.581  0.183        1.0    0.000
29  6_histogram   Sensitivity_1  0.868  0.123        0.0    0.541
31  6_histogram     Precision_1  0.812  0.138        1.0    0.000
33  5_ss_shared          Dice_1  0.869  0.097        1.0    0.016
35  5_ss_shared  Surface_dice_1  0.700  0.187        1.0    0.013
37  5_ss_shared   Sensitivity_1  0.872  0.119        0.0    0.528
39  5_ss_shared     Precision_1  0.876  0.105        1.0    0.028

In [161]:
make_main_table(folder, '3a_atlas_f', ['7a_resample'], ['Dice_1','Surface_dice_1','Hausdorff95_1'], df_fold_0, df_fold_1, df_fold_2)

    Experiment          Metric    Mean     STD  criterion  p_value
0   3a_atlas_f          Dice_1   0.857   0.106        NaN      NaN
1  7a_resample          Dice_1   0.848   0.111        1.0    0.001
2   3a_atlas_f  Surface_dice_1   0.668   0.195        NaN      NaN
3  7a_resample  Surface_dice_1   0.642   0.196        1.0    0.000
4   3a_atlas_f   Hausdorff95_1  16.456  22.126        NaN      NaN
5  7a_resample   Hausdorff95_1  19.466  25.954        0.0    0.163

In [162]:
make_main_table(folder, '1_reg_f', ['1_reg_aug'], ['Dice_1','Surface_dice_1','Hausdorff95_1'], df_fold_0, df_fold_1, df_fold_2)

  Experiment          Metric    Mean     STD  criterion  p_value
0    1_reg_f          Dice_1   0.429   0.273        NaN      NaN
1  1_reg_aug          Dice_1   0.430   0.270        1.0    0.046
2    1_reg_f  Surface_dice_1   0.251   0.138        NaN      NaN
3  1_reg_aug  Surface_dice_1   0.259   0.139        1.0    0.004
4    1_reg_f   Hausdorff95_1  35.266  21.420        NaN      NaN
5  1_reg_aug   Hausdorff95_1  38.168  29.400        0.0    0.859

In [169]:
make_main_table(folder, '3a_atlas_f', ['3b_n4_f','3a_susan','3c_n4_susan','6_histogram'], 
                ['Dice_1','Surface_dice_1','Hausdorff95_1'], df_fold_0, df_fold_1, df_fold_2).drop_duplicates(['Experiment', 'Metric'])

     Experiment          Metric    Mean     STD  criterion  p_value
0    3a_atlas_f          Dice_1   0.857   0.106        NaN      NaN
1       3b_n4_f          Dice_1   0.844   0.113        1.0    0.019
2    3a_atlas_f  Surface_dice_1   0.668   0.195        NaN      NaN
3       3b_n4_f  Surface_dice_1   0.638   0.199        1.0    0.001
4    3a_atlas_f   Hausdorff95_1  16.456  22.126        NaN      NaN
5       3b_n4_f   Hausdorff95_1  13.821  21.235        0.0    0.358
7      3a_susan          Dice_1   0.723   0.245        1.0    0.001
9      3a_susan  Surface_dice_1   0.535   0.256        1.0    0.000
11     3a_susan   Hausdorff95_1  23.167  27.147        1.0    0.003
13  3c_n4_susan          Dice_1   0.839   0.118        1.0    0.000
15  3c_n4_susan  Surface_dice_1   0.625   0.200        1.0    0.000
17  3c_n4_susan   Hausdorff95_1  17.535  23.479        0.0    0.055
19  6_histogram          Dice_1   0.829   0.114        1.0    0.000
21  6_histogram  Surface_dice_1   0.581   0.183        1.0    0.000
23  6_histogram   Hausdorff95_1  25.364  28.372        1.0    0.002

In [13]:
os.listdir('../log_gbm/results/')

['metrics_gbm_1_reg_aug_fold-2.csv',
 'metrics_gbm_1_reg_aug_fold-0.csv',
 'metrics_gbm_5_ss_shared_fold-1_label_from_3atlas.csv',
 'metrics_gbm_2a_interp_fold-0.csv',
 'metrics_gbm_2b_n4_fold-2.csv',
 'metrics_gbm_3a_atlas_fold-2.csv',
 'metrics_gbm_6_histogram_fold_2_fold-2.csv',
 'metrics_gbm_3b_n4_fold-1.csv',
 'metrics_gbm_3a_susan_fold-1.csv',
 'metrics_gbm_2a_interp_fold-1.csv',
 'metrics_gbm_TCGA_GBM_fold-2.csv',
 'metrics_gbm_3aatlas_withoutbrain_label_from_3aatlas_fold-1.csv',
 'metrics_gbm_5_ss_shared_fold-2_label_from_3atlas.csv',
 'metrics_gbm_3a_susan_fold-2.csv',
 'metrics_gbm_1_reg_fold-1.csv',
 'metrics_gbm_TCGA_GBM_fold-1.csv',
 'metrics_gbm_5_ss_shared_fold-1.csv',
 'metrics_gbm_3a_atlas_fold-1.csv',
 'metrics_gbm_3c_n4_susan_fold-0.csv',
 'metrics_gbm_2b_n4_fold-0.csv',
 'metrics_gbm_6_histogram_fold_1_fold-1.csv',
 'metrics_gbm_2c_n4_susan_fold-0.csv',
 'metrics_gbm_3aatlas_withoutbrain_label_from_3aatlas_fold-0.csv',
 'metrics_gbm_3c_n4_susan_fold-1.csv',
 'metrics_gbm_3c_n4_susan_fold-2.csv',
 'metrics_gbm_2a_interp_fold-2.csv',
 'metrics_gbm_5_ss_shared_fold-2.csv',
 'metrics_gbm_7a_resample_fold-1.csv',
 'metrics_gbm_1_reg_fold-2.csv',
 'metrics_gbm_6_histogram_fold_0_fold-0.csv',
 'metrics_gbm_7a_resample_fold-0.csv',
 'metrics_gbm_3b_n4_fold-0.csv',
 'metrics_gbm_1_reg_aug_fold-1.csv',
 'metrics_gbm_2c_n4_susan_fold-1.csv',
 'metrics_gbm_1_reg_fold-0.csv',
 'metrics_gbm_2a_interp_aug_fold-0.csv',
 'metrics_gbm_2c_n4_susan_fold-2.csv',
 'metrics_gbm_2a_interp_aug_fold-2.csv',
 'metrics_gbm_2b_n4_fold-1.csv',
 'metrics_gbm_2a_interp_aug_fold-1.csv',
 'metrics_gbm_3aatlas_withoutbrain_label_from_3aatlas_fold-2.csv',
 'metrics_gbm_3b_n4_fold-2.csv',
 'metrics_gbm_5_ss_shared_fold-0_label_from_3atlas.csv',
 'metrics_gbm_7a_resample_fold-2.csv',
 'metrics_gbm_3a_atlas_fold-0.csv']

In [ ]:
temp_df = pd.read_csv('../log_gbm/results/')